repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: trailing-whitespace
    - id: check-merge-conflict

-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.6
    hooks:
    - id: clang-format
      name: "Clang Format"

-   repo: local
    hooks:
    - id: gazelle
      name: "Gazelle linting"
      entry: bazel run //:gazelle -- update
      pass_filenames: false
      files: 'BUILD|BUILD.bazel'
      language: system